### ISSUE TITLE
[Idea] Discussion Page

### ISSUE THREAD

**Issue by kookma** [satran/tiddlygo#1]
Is it possible to activate the discussion page for this lovely project?

There are occasions one can discuss feature or an idea which is NOT an issue!

This project can get a lot of attention as saving locally and serving on local server specially for people with little web/technical knowledge is very useful! Most users of Tiddlywiki have little or no technical knowledge of servers and like that!

I also recommend to have a look at https://links.tiddlywiki.com/

* https://talk.tiddlywiki.org/t/custom-application-for-tiddlywiki-based-on-webdav/944
* https://talk.tiddlywiki.org/t/webdav-for-saving-single-file-wiki/146

**Comment by kookma** [comment]
I highly recommend to see https://saqimtiaz.github.io/tw5-file-uploads/ from @saqimtiaz who is the pioneer developer in the area!

**Comment by satran** [comment]
Thanks for the idea. I have enabled it. 
I guess my skills at searching for plugins were not that great. It definitely looks interesting. I was considering a GitHub plugin as well. I'll have a look.
